{
    'name': 'OxyCure',
    'version': '18.0.1.0.0',
    'summary': 'OxyCure Hospital Management System',
    'description': """
OxyCure Hospital Management System
===================================
Custom Hospital Management Module
""",
    'author': 'Nimya Thomas',
    'website': '',
    'category': 'Healthcare',
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    
    'data': [
        'security/ir.model.access.csv',
        'data/patient_sequence.xml',
        'data/department_sequence.xml',
        'data/doctor_sequence.xml',
        'data/appointment_sequence.xml',
        'data/op_sequence.xml',
        'data/lab_request_sequence.xml',
        'data/billing_sequence.xml',
        'data/pharmacy_sequence.xml',
        'data/pharmacy_cron.xml',
        'data/billing_email_template.xml',
        'views/patient_views.xml',
        'views/department_views.xml',
        'views/doctor_views.xml',
        'views/appointment_views.xml',
        'views/op_views.xml',
        'views/medicine_views.xml',
        'views/medicine_category_views.xml',
        'views/medicine_supplier_views.xml',
        'views/medicine_batch_views.xml',
        'views/medicine_purchase_views.xml',
        'views/purchase_return_views.xml',
        'views/patient_return_views.xml',
        'views/stock_adjustment_views.xml',
        'views/expired_disposal_views.xml',
        'views/stock_movement_views.xml',
        'views/pharmacy_sale_views.xml',
        'views/pharmacy_alert_views.xml',
        'views/lab_test_views.xml',
        'views/lab_operations_views.xml',
        'views/lab_equipment_views.xml',
        'views/billing_views.xml',
        'views/billing_tv_views.xml',
        'views/billing_dashboard_views.xml',
        'views/billing_report.xml',
        'views/pharmacy_views.xml',
        'views/dashboard_views.xml',
        'views/op_queue_views.xml',
        'views/op_document_views.xml',
        'views/lab_queue_views.xml',
        'views/pharmacy_queue_views.xml',
        'views/op_tv_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'hospital_management/static/src/components/stt_recorder/stt_recorder.js',
            'hospital_management/static/src/components/stt_recorder/stt_recorder.xml',
            'hospital_management/static/src/components/stt_recorder/stt_recorder.css',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}