from . import patient
from . import department
from . import doctor
from . import appointment
from . import op
from . import prescription
from . import medicine
from . import lab_test
from . import lab_request
from . import lab_processing
from . import billing
from . import pharmacy
from . import dashboard